plugins {
    id "architectury-plugin" version "3.4-SNAPSHOT"
    id "dev.architectury.loom" version "1.10.437" apply false
}

architectury {
    minecraft = rootProject.minecraft_version
}

subprojects {
    apply plugin: "dev.architectury.loom"

    loom {
        silentMojangMappingsLicense()
    }

    dependencies {
        minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
        mappings loom.officialMojangMappings()
    }
}

allprojects {
    apply plugin: "java"
    apply plugin: "architectury-plugin"
    apply plugin: "maven-publish"

    base {
        archivesName = rootProject.archives_base_name
    }

    version = rootProject.mod_version
    group = rootProject.maven_group

    repositories {
        mavenCentral()
        maven { url = "https://maven.neoforged.net/releases" }
        maven { url = "https://maven.terraformersmc.com/releases" }
    }

    tasks.withType(JavaCompile) {
        options.encoding = "UTF-8"
        options.release = 21
        options.compilerArgs.add("-Xlint:all,-processing")
    }

    java {
        withSourcesJar()
    }
}

tasks.register("publishModrinthAll") {
    group = "publishing"
    dependsOn(":fabric:modrinth", ":neoforge:modrinth")
}

tasks.register("publishCurseForgeAll") {
    group = "publishing"
    dependsOn(":fabric:curseforge1724459", ":neoforge:curseforge1724459")
}

tasks.register("publishAll") {
    group = "publishing"
    dependsOn("publishModrinthAll", "publishCurseForgeAll")
}
